% extendSimulations.m
% Extends the simulation duration of exsiting cases

clearvars; close all; clc;
addpath('..\src');
cd ..\ % Working from the top folder

% inputfiles = ["BRDcase1.m","BRDcase2.m","BRDcase3.m","BRDcase4.m","BRDcase5.m",...
%         "BRDcase6.m","BRDcase7.m","BRDcase8.m","BRDcase9.m","BRDcase10.m",...
%         "BRDcase11.m","BRDcase12.m","BRDcase13.m","BRDcase14.m","BRDcase15.m",...
%         "BRDcase16.m","BRDcase17.m","BRDcase18.m","BRDcase19.m","BRDcase20.m",...
%         "BRDcase21.m","BRDcase22.m","BRDcase23.m","BRDcase24.m","BRDcase25.m",...
%         "BRDcase26.m","BRDcase27.m","BRDcase28.m","BRDcase29.m","BRDcase30.m",...
%         "BRDcase31.m","BRDcase32.m","BRDcase33.m","BRDcase34.m","BRDcase35.m",...
%         "BRDcase36.m","BRDcase37.m","BRDcase38.m","BRDcase39.m","BRDcase40.m",...
%         "BRDcase41.m","BRDcase42.m","BRDcase43.m","BRDcase44.m","BRDcase45.m",...
%         "BRDcase46.m","BRDcase47.m","BRDcase48.m","BRDcase49.m","BRDcase50.m"];
% inputfiles = ["BRDcase1Extended.m","BRDcase2Extended.m","BRDcase3Extended.m","BRDcase4Extended.m","BRDcase5Extended.m",...
%             "BRDcase6Extended.m","BRDcase7Extended.m","BRDcase8Extended.m","BRDcase9Extended.m","BRDcase10Extended.m",...
%             "BRDcase11Extended.m","BRDcase12Extended.m","BRDcase13Extended.m","BRDcase14Extended.m","BRDcase15Extended.m",...
%             "BRDcase16Extended.m","BRDcase17Extended.m","BRDcase18Extended.m","BRDcase19Extended.m","BRDcase20Extended.m",...
%             "BRDcase21Extended.m","BRDcase22Extended.m","BRDcase23Extended.m","BRDcase24Extended.m","BRDcase25Extended.m",...
%             "BRDcase26Extended.m","BRDcase27Extended.m","BRDcase28Extended.m","BRDcase29Extended.m","BRDcase30Extended.m",...
%             "BRDcase31Extended.m","BRDcase32Extended.m","BRDcase33Extended.m","BRDcase34Extended.m","BRDcase35Extended.m",...
%             "BRDcase36Extended.m","BRDcase37Extended.m","BRDcase38Extended.m","BRDcase39Extended.m","BRDcase40Extended.m",...
%             "BRDcase41Extended.m","BRDcase42Extended.m","BRDcase43Extended.m","BRDcase44Extended.m","BRDcase45Extended.m",...
%             "BRDcase46Extended.m","BRDcase47Extended.m","BRDcase48Extended.m","BRDcase49Extended.m","BRDcase50Extended.m"];
% inputfiles = ["case1.m","case14.m","case15.m","case16.m","case17.m","case18.m",...
%     "case19.m","case20.m","case21.m","case22.m","case23.m"];
inputfiles = ["caseBO1.m","caseBO2.m","caseBO3.m","caseBO4.m","caseBO5.m",...
        "caseBO6.m","caseBO7.m","caseBO8.m","caseBO9.m","caseBO10.m",...
        "case2.m","case3.m","case4.m","case5.m",...
        "case6.m","case7.m","case8.m","case9.m","case10.m","case11.m"];

extendedTspan = 0:0.2:3600;
for i=1:1:numel(inputfiles)
    sim = simulation.loadsim(inputfiles(i));
    % make the position and orinetation of the vehicle the mean over the last half of the simualtion.  
    sim.vhcl.orientation = [mean(sim.states(:,4));mean(sim.states(:,5));mean(sim.states(:,6))];
    sim.vhcl.position = [mean(sim.states(:,1));mean(sim.states(:,2));mean(sim.states(:,3))];
    sim.changeName([sim.name 'Extended'],'Sure');
    sim.simulate('tspan',extendedTspan,'stats','on','output',[]);
    sim.write2file;
end
 
% Go back to the tools folder
cd tools