% renameSimulations.m
% For renaming and rewriting simulations in bulk

clearvars; close all; clc;

addpath('..\src');
cd ..\ % Working from the top folder

% inputfiles = ["case1Extended.m","case2Extended.m","case3Extended.m","case4Extended.m","case5Extended.m","case6Extended.m",...
%         "caseBO6Extended.m","caseBO7Extended.m","caseBO8Extended.m","caseBO9Extended.m","caseBO10Extended.m",...
%     "case14Extended.m","BRDcase41Extended.m","BRDcase42Extended.m","BRDcase43Extended.m","BRDcase44Extended.m","BRDcase45Extended.m",...
%         "BRDcase46Extended.m","BRDcase47Extended.m","BRDcase48Extended.m","BRDcase49Extended.m","BRDcase50Extended.m",...
%     "case15Extended.m","BRDcase31Extended.m","BRDcase32Extended.m","BRDcase33Extended.m","BRDcase34Extended.m","BRDcase35Extended.m",...
%         "BRDcase36Extended.m","BRDcase37Extended.m","BRDcase38Extended.m","BRDcase39Extended.m","BRDcase40Extended.m",...
%     "case20Extended.m","BRDcase21Extended.m","BRDcase22Extended.m","BRDcase23Extended.m","BRDcase24Extended.m","BRDcase25Extended.m",...
%         "BRDcase26Extended.m","BRDcase27Extended.m","BRDcase28Extended.m","BRDcase29Extended.m","BRDcase30Extended.m",...
%      "case19Extended.m","BRDcase11Extended.m","BRDcase12Extended.m","BRDcase13Extended.m","BRDcase14Extended.m","BRDcase15Extended.m",...
%         "BRDcase16Extended.m","BRDcase17Extended.m","BRDcase18Extended.m","BRDcase19Extended.m","BRDcase20Extended.m",...
%     "case18Extended.m","BRDcase1ExtendedExtended.m","BRDcase2Extended.m","BRDcase3Extended.m","BRDcase4Extended.m","BRDcase5Extended.m",...
%         "BRDcase6Extended.m","BRDcase7Extended.m","BRDcase8Extended.m","BRDcase9Extended.m","BRDcase10Extended.m"];
itr = 1;
for i=66:-1:38
            inputfiles(itr) = strcat("DB2case",num2str(i),".m");
            itr = itr + 1;
end
itr = 66;
for i=1:1:numel(inputfiles)
    sim = simulation.loadsim(inputfiles(i));
    sim.changeName(['EF3correctICsCase' num2str(itr)],'Sure');
    sim.write2file;
    itr = itr - 1;
end
 
% Go back to the tools folder
cd tools